{
 "title": "State",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "grafana-clock-panel", "description": "Clock", "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Server Resource Overview",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "targets": [
    { "expr": "node_uname_info - 0" },
    {
     "expr": "sum(time() - node_boot_time_seconds)by(instance)"
    },
    { "expr": "node_memory_MemTotal_bytes - 0" },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)"
    },
    { "expr": "node_load5", "legendFormat": "avg5" },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance)) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{device=\"vda\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{device=\"vda\"}[$__rate_interval])) by (instance)"
    },
    { "expr": "node_netstat_Tcp_CurrEstab - 0" },
    { "expr": "node_sockstat_TCP_tw - 0", "legendFormat": "TIME_WAIT" },
    {
     "expr": "max(rate(node_network_receive_bytes_total[$__rate_interval])*8) by (instance)"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total[$__rate_interval])*8) by (instance)"
    }
   ]
  },
  { "title": "По каждому серверу", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Uplink",
   "type": "timeseries",
   "description": "Доступность сервера",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"app02.mydomain:9100\"}"
    }
   ]
  },
  {
   "title": "Uplink",
   "type": "timeseries",
   "description": "Доступность сервера",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"app01.mydomain:9100\"}"
    }
   ]
  },
  {
   "title": "Uplink",
   "type": "timeseries",
   "description": "Доступность сервера",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"mon01.mydomain:9100\"}"
    }
   ]
  },
  {
   "title": "Uplink all",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uplink",
   "type": "timeseries",
   "description": "Доступность сервера",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"db01.mydomain:9100\"}"
    }
   ]
  },
  {
   "title": "Uplink",
   "type": "timeseries",
   "description": "Доступность сервера",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"db02.mydomain:9100\"}"
    }
   ]
  },
  {
   "title": "Uplink",
   "type": "timeseries",
   "description": "Доступность сервера",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"db03.mydomain:9100\"}"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Busy %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"app01.mydomain:9100\"}) by (cpu))) - avg(sum by (mod)(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"app01.mydomain:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"app01.mydomain:9100\"}) by (cpu))",
     "legendFormat": "app01.mydomain"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"app02.mydomain:9100\"}) by (cpu))) - avg(sum by (mod)(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"app02.mydomain:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"app02.mydomain:9100\"}) by (cpu))",
     "legendFormat": "app02.mydomain"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"db01.mydomain:9100\"}) by (cpu))) - avg(sum by (mod)(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"db01.mydomain:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"db01.mydomain:9100\"}) by (cpu))",
     "legendFormat": "db01.mydomain"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"db02.mydomain:9100\"}) by (cpu))) - avg(sum by (mod)(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"db02.mydomain:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"db02.mydomain:9100\"}) by (cpu))",
     "legendFormat": "db02.mydomain"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"db03.mydomain:9100\"}) by (cpu))) - avg(sum by (mod)(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"db03.mydomain:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"db03.mydomain:9100\"}) by (cpu))",
     "legendFormat": "db03.mydomain"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"mon01.mydomain:9100\"}) by (cpu))) - avg(sum by (mod)(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"mon01.mydomain:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"mon01.mydomain:9100\"}) by (cpu))",
     "legendFormat": "mon01.mydomain"
    }
   ]
  },
  {
   "title": "утилизация памяти",
   "type": "timeseries",
   "description": "all in",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "100*(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)/node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"app01.mydomain:9100\",job=\"node_exporter\"}",
     "legendFormat": "app01.mydomain"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"app02.mydomain:9100\",job=\"node_exporter\"}",
     "legendFormat": "app02.mydomain"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"mon01.mydomain:9100\",job=\"node_exporter\"}",
     "legendFormat": "mon01.mydomain"
    }
   ]
  },
  {
   "title": "SWAP all",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)/(node_memory_SwapTotal_bytes))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"db01.mydomain:9100\",job=\"node_exporter\"}",
     "legendFormat": "db0101.mydomain"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"db02.mydomain:9100\",job=\"node_exporter\"}",
     "legendFormat": "db0201.mydomain"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"db03.mydomain:9100\",job=\"node_exporter\"}",
     "legendFormat": "db03.mydomain"
    }
   ]
  },
  {
   "title": "свободное дисковое пространство",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(node_filesystem_avail_bytes{mountpoint=\"/\"})/node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "свободное дисковое пространство",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}/1024/1024/1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "задержка диска",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{device=\"vda\"}[1m]) / rate(node_disk_reads_completed_total{device=\"vda\"}[1m])",
     "legendFormat": "{{instance}} {{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{device=\"vda\"}[1m]) / rate(node_disk_writes_completed_total{device=\"vda\"}[1m])",
     "legendFormat": "{{instance}} {{device}}_Write time"
    }
   ]
  },
  {
   "title": "iops",
   "type": "graph",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "утилизация сети (receive)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total[5m])*8) by (instance)",
     "legendFormat": "{{instanse}}"
    }
   ]
  },
  {
   "title": "утилизация сети1 (transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total[5m])*8) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "успешность резервного копирования",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 82 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "db02" }
     ]
    },
    {}
   ]
  },
  {
   "title": "Серверы приложений",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true
  },
  {
   "title": "количество соединений на nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nginx",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active_mon01" ], "type": "alias" }
      ],
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "waiting_mon01" ], "type": "alias" }
      ],
      [
       { "params": [ "writing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "writing_mon01" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mon01" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nginx",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active_app01" ], "type": "alias" }
      ],
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "waiting_app01" ], "type": "alias" }
      ],
      [
       { "params": [ "writing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "writing_app01" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "app01" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nginx",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active_app02" ], "type": "alias" }
      ],
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "waiting_app02" ], "type": "alias" }
      ],
      [
       { "params": [ "writing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "writing_app02" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "app02" }
     ]
    }
   ]
  },
  {
   "title": "наличие и количество кодов ответа 5xx",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 94 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "https://mydomain" },
      { "condition": "AND", "key": "status_code", "operator": ">", "value": "500" }
     ]
    }
   ]
  },
  {
   "title": "успешность синхронизации файлов между app01 - 02",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 94 }
  },
  { "title": "Серверы баз данных", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "состояние кластера (все ли ноды онлайн)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "MySQL Cluster",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "wsrep_cluster_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "db01" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "db02" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "db03" }
     ]
    }
   ]
  },
  {
   "title": "количество обращений в бд",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 99 },
   "targets": [
    {
     "alias": "MySQL Cluster",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "threads_connected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "db01" }
     ]
    }
   ]
  },
  {
   "title": "наличие длинных запросов (выполняющихся более 5с)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Slow Queries",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "queries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Общие по проекту",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true
  },
  {
   "title": "доступность “главной страницы”",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "alias": "https://mydomain",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "result", "operator": "=", "value": "success" },
      { "condition": "AND", "key": "server", "operator": "=", "value": "https://mydomain" }
     ]
    }
   ]
  },
  {
   "title": "время ответа “главной страницы”",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT non_negative_derivative(mean(\"requests\"),1s) AS \"requests\" FROM \"nginx\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "https://mydomain" }
     ]
    }
   ]
  },
  {
   "title": "наличие кодов ответа, отличных от 200",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 116 },
   "targets": [
    {
     "alias": "https://mydomain",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "https://mydomain" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "success" }
     ]
    }
   ]
  },
  { "title": "срок делегирования домена", "type": "timeseries", "gridPos": { "h": 6, "w": 9, "x": 9, "y": 116 } },
  {
   "title": "срок действия ssl сертификата",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "x509_cert",
     "select": [
      [
       { "params": [ "expiry" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/60/60/24" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "file:///etc/letsencrypt/live/grafana.mydomain/cert.pem"
      }
     ]
    }
   ]
  },
  {
   "title": "срок действия ssl сертификата",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "x509_cert",
     "query": "SELECT last(\"http_response_code\") FROM \"http_response\" WHERE (\"server\" =~ /^$url_name$/) AND $timeFilter GROUP BY server",
     "select": [
      [
       { "params": [ "expiry" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/60/60/24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mon01" },
      {
       "condition": "AND",
       "key": "source",
       "operator": "=",
       "value": "file:///etc/letsencrypt/live/grafana.mydomain/cert.pem"
      }
     ]
    }
   ]
  }
 ]
}